### ISSUE TITLE
dbus-call-method error message + Dashboard editable

### ISSUE THREAD

**Issue by GiulioCentorame** [MatthewZMD/.emacs.d#17]
**Describe the bug**
In a fresh installation, after restarting the program, I get the following error: `dbus-call-method: Cannot open load file: No such file or directory, org-tempo
`

The dashboard is also editable and with ^L character despite having installed page-break-lines separately. No dashboard link is working.

**To Reproduce**
Installed the whole thing as per instructions. I skipped some dependencies for Java.

**Expected behavior**
Startup without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Manjaro (xfce)
 - Browser: Firefox 69.0.3

**Comment by MatthewZMD** [comment]
What emacs version are you having? Can you try (emacs-version)

**Comment by GiulioCentorame** [comment]
`GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29`

`Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.3/lisp/org/)`

**Comment by MatthewZMD** [comment]
@GiulioCentorame Try to git pull again, I've created a new [commit](https://github.com/MatthewZMD/.emacs.d/commit/578ce796360d801e59cccfdb64b7cc94cba5fb53)

**Comment by GiulioCentorame** [comment]
It's working, thank you!
