### ISSUE TITLE
how to add custom config without modifiying your config

### ISSUE THREAD

**Issue by oouxx** [MatthewZMD/.emacs.d#20]
I changed the mirror to tencent a few days ago.Today I git pull the code.I am annoyed by the merge conflicts.there ia a way that I can add custom config without modifying your config

**Comment by MatthewZMD** [comment]
This is more of a git issue

2 possible solutions:

1. You can simply create a new file, require it in init.el, and add it to .gitignore, anything there will not be affected by my changes.

2. If you want to ignore sections of a file, maybe check out something like this here:
 https://stackoverflow.com/questions/16244969/how-to-tell-git-to-ignore-individual-lines-i-e-gitignore-for-specific-lines-of

**Comment by oouxx** [comment]
Thanks. I will have a try.
