### ISSUE TITLE
Not running from a custom path?

### ISSUE THREAD

**Issue by AndreaCrotti** [MatthewZMD/.emacs.d#21]
**Describe the bug**
I just wanted  to try this config out, and I checked out the project in a directory that it's not my `~/.emacs.d`
Trying to load the `init.el` file manually fails though, probably simply because the local dir is not in the `load-path`.

**Comment by MatthewZMD** [comment]
Can you paste the error message?

**Comment by AndreaCrotti** [comment]
You would get something like `let*: Opening input file: No such file or directory, /home/andrea/.emacs.d/early-init.el`
After checking out the project locally and running Emacs from there:
`~/p/f/memacs> emacs -q`

**Comment by MatthewZMD** [comment]
> After checking out the project locally and running Emacs from there:

Wait, you still have another set of configurations in `~/.emacs.d/`? Is that what `C-h v user-emacs-directory` shows?

Because it does not matter at which directory you run Emacs from, it will look at either `~/.emacs.d/` or `~/.config/emacs` (latter for xdg config) for Emacs configurations. If you clone M-EMACS into another directory other than these two, Emacs does not know it.

**Comment by AndreaCrotti** [comment]
Well I ran emacs -q which doesn't try to load anything afaik, the problem is just my local directory not in load path I guess, I'll try it out

**Comment by MatthewZMD** [comment]
I'm not sure if I correctly understand your situation, but `emacs -q` is not supposed to load anything.

```
-q, --no-init-file
  Do not load an init file.
```

**Comment by AndreaCrotti** [comment]
Yes I know I load your init.el file after a fresh emacs is started and I just do eval-buffer for example

**Comment by MatthewZMD** [comment]
Oh, I see what you mean. Yep if you only `eval-buffer` the `init.el`, it does not know where all the `(require init-xx)` are located. You need them to be in the load-path
