### ISSUE TITLE
Code blocks are not decoupled

### ISSUE THREAD

**Issue by justinekizhak** [MatthewZMD/.emacs.d#22]
**Describe the bug**
The `Garbage Collect When Emacs is Out of Focus` and 
`Avoid Garbage Collect When Using Minibuffer` code blocks are not decoupled from each other.   

The first block is missing 2 closing parentheses and the second block has 2 additional closing parentheses.

My understanding is that the lower block is supposed to be inside `emacs-startup-hook`. 

But if someone copies just the lower or just the upper block they will face syntax error.

Code blocks in question:

1. [Garbage Collect When Emacs is Out of Focus](https://github.com/MatthewZMD/.emacs.d#garbage-collect-when-emacs-is-out-of-focus)

2. [Avoid Garbage Collect When Using Minibuffer](https://github.com/MatthewZMD/.emacs.d#avoid-garbage-collect-when-using-minibuffer)

**Expected behavior**
User can copy either of the code blocks and doesn't have double-check if all the required parenthesis are present or not.

**Possible solutions**
1. Combine both code blocks or
2. Mention that both the code blocks should be copied and pasted in the same order or
3. Add closing parenthesis to the first block and put the second block inside the hook

**Comment by MatthewZMD** [comment]
Thanks for letting me know, I thought separating these two will be clearer. This is fixed now.
