### ISSUE TITLE
[Question] https and signature verification on elpa 

### ISSUE THREAD

**Issue by efouladi** [MatthewZMD/.emacs.d#23]
I was wondering if there is any particular reason for not using https on elpa and removing the gnu-elpa-keyring-update?

Isn't this a potential security risk?

**Comment by MatthewZMD** [comment]
> not using https on elpa 

No, it's an overlook. Thanks for noticing :)

> removing the gnu-elpa-keyring-update?

For those on version >= 26.3, the keyring has already been updated for them. For those lower, the keyring has already expired and they cannot simply use `use-package` to update keyring: it will fail before getting there. They have to manually install gnu-elpa-keyring-update elsewhere and follow stackoverflow or reddit answers to properly set it up. I figured this part of config cannot properly help them, so I removed it.
