### ISSUE TITLE
remove toolbar

### ISSUE THREAD

**Issue by dagnachewa** [MatthewZMD/.emacs.d#24]
I added (tool-bar-mode -1) in init-ui-config.el and it did not work

**Comment by MatthewZMD** [comment]
> I added (tool-bar-mode -1) in init-ui-config.el and it did not work

The part disabling tool-bar-mode is in the `early-init.el` file instead of `init-ui-config.el`.

```
;; DisableUnnecessaryInterface
(menu-bar-mode -1)
(unless (and (display-graphic-p) (eq system-type 'darwin))
  (push '(menu-bar-lines . 0) default-frame-alist))
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(vertical-scroll-bars) default-frame-alist)
;; -DisableUnnecessaryInterface
```

I am sorry if it seems a little bit confusing with the naming, but it is much nicer to disable these troublesome interfaces at the most beginning of Emacs startup process.

Anyways, this setting has already been set for you. You shouldn't need to add `(tool-bar-mode -1)` yourself.


Matthew

**Comment by dagnachewa** [comment]
I am using the 2bwm wm and when I start emacs It looks like this
https://imgur.com/a/VfSuJDS
but after I position the emacs app to the center the menubar disappears and
it looks like this https://imgur.com/a/GfxUahf
this is what I wanted, but was just confused at why I was seeing the menu
bar
thanks.

How can enable more languages ? do you think you will have a module system
where we can enable/disable plugins like languages and apps?
Thanks for your time

**Comment by MatthewZMD** [comment]
> I am using the 2bwm wm and when I start emacs It looks like this https://imgur.com/a/VfSuJDS but after I position the emacs app to the center the menubar disappears and it looks like this https://imgur.com/a/GfxUahf this is what I wanted, but was just confused at why I was seeing the menu bar thanks.
    
This is very weird. What Emacs version are you on? M-x emacs-version

> How can enable more languages ? do you think you will have a module system where we can enable/disable plugins like languages and apps?

Currently it doesn't have a module system, and I'm not sure whether I should add it as IMO it unnecessarily complicates the configuration.

If you want to add any new packages (such as languages) you can create a new file, and require it in `init.el`. If you want to disable any package, you just need to add a `:disabled` tag in `(use-package`. Or you can comment out the corresponding `(require 'init-xx)` line in `init.el`

**Comment by dagnachewa** [comment]
Last question, is it possible to customize the dashboard to make it look
like doom-emacs with the icons ?

**Comment by MatthewZMD** [comment]
> Last question, is it possible to customize the dashboard to make it look
> like doom-emacs with the icons ?

AFAIK, Doom Emacs uses its own [dashboard](https://github.com/hlissner/doom-emacs/tree/develop/modules/ui/doom-dashboard) and I use [emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard). I haven't look into the source code nor have I tried Doom Emacs, I'm not sure how similar are these two dashboards.

**Comment by dagnachewa** [comment]
I succeeded to change the dashboard to my liking https://imgur.com/a/u0snSBe
but I wanted to enable doom-modeline it does not enable doom-modeline on
startup
where can we declare the modeline globally with all the segments enabled, I
think it's the 'main

**Comment by MatthewZMD** [comment]
Doom-modeline by default does enable on startup

**Comment by dagnachewa** [comment]
I dont see the git icons in git files

**Comment by dagnachewa** [comment]
here are three images on startup no icons on modeline, after I do m-x
doom-modeline enable I see the last two images, https://imgur.com/a/Y2KEeXM

I would like to have on the modeline the whole segments, please help, I
have to activate doom-modeline-def-modeline-main ? it seem to have all the
segments
where should I configure the modeline with all the segments on every buffer.

Thanks again for your time, I was on doom-emacs without evil-mode learning
emacs with the book mastering emacs on half the screen, then I stumbled on
your config, and then am back again on config ... all your fault ;)
is it possible to divide the dashboard half / half, left side
recent,bookmarks right side other stuff ? can we change the colour of the
characters ??

**Comment by MatthewZMD** [comment]
What Emacs version are you using?

> here are three images on startup no icons on modeline, after I do m-x
> doom-modeline enable I see the last two images, https://imgur.com/a/Y2KEeXM

```
(use-package doom-modeline
  :hook (after-init . doom-modeline-mode)
```

This line adds doom-modeline-mode to after-init-hook, that means doom-modeline is opened by default after initializing Emacs.

> I would like to have on the modeline the whole segments, please help, I
> have to activate doom-modeline-def-modeline-main ? it seem to have all the
> segments
> where should I configure the modeline with all the segments on every buffer.

What are segments? And what is doom-modeline-def-modeline-main?

> Thanks again for your time, I was on doom-emacs without evil-mode learning
> emacs with the book mastering emacs on half the screen, then I stumbled on
> your config, and then am back again on config ... all your fault ;)

Haha no worries ;)

> is it possible to divide the dashboard half / half, left side
> recent,bookmarks right side other stuff ?

For this particular feature, you are better off asking the developers of doom-modeline, I am not very familiar with it.

> can we change the colour of the
> characters ??

C-s defface in doom-modeline-core.el to see all available faces and M-x customize-face

**Comment by dagnachewa** [comment]
26.3

**Comment by MatthewZMD** [comment]
This has been fixed
