### ISSUE TITLE
byte-compile errors after reinstalling it

### ISSUE THREAD

**Issue by GiulioCentorame** [MatthewZMD/.emacs.d#27]
**Describe the bug**
Reinstalled everything (`rm -rf` the past `.emacs.d` folder) and had an infinite list of warnings:

`Compiling file /home/giuliocentorame/.emacs.d/elpa/2048-game-20151026.1933/2048-game.el at Fri Jan 10 18:06:57 2020
Entering directory ‘/home/giuliocentorame/.emacs.d/elpa/2048-game-20151026.1933/’
Warning (bytecomp): reference to free variable ‘apu--package-installation-results’
Warning (bytecomp): assignment to free variable ‘apu--package-installation-results’
Warning (bytecomp): Unused lexical variable ‘ido-setup-hook’
Warning (bytecomp): reference to free variable ‘ido-setup-hook’
Warning (bytecomp): Unused lexical variable ‘remote-user’
Warning (bytecomp): reference to free variable ‘undo-tree-mode’
Warning (bytecomp): ‘undo-elt-crosses-region’ is an obsolete function (as of 25.1). [2 times]
Warning (bytecomp): reference to free variable ‘undo-tree-visualizer-selection-mode’ [2 times]
Warning (bytecomp): reference to free variable ‘web-mode-content-type’
Warning (bytecomp): reference to free variable ‘neo-global--window’
Warning (bytecomp): assignment to free variable ‘hl-line-sticky-flag’
Warning (bytecomp): reference to free variable ‘neo-vc-integration’
Warning (bytecomp): reference to free variable ‘neotree-dir-button-keymap’
Warning (bytecomp): reference to free variable ‘neo-vc-integration’
Warning (bytecomp): reference to free variable ‘neotree-file-button-keymap’
Warning (bytecomp): assignment to free variable ‘neo-vc-integration’
Warning (bytecomp): the following functions are not known to be defined:
    neo-path--file-short-name, neo-vc-for-node,
    neo-buffer--insert-fold-symbol, neo-buffer--node-list-set,
    neo-buffer--newline-and-begin, neo-global--select-window,
    neo-buffer--insert-file-entry, neo-buffer--insert-dir-entry,
    neo-buffer--insert-root-entry
Warning (bytecomp): reference to free variable ‘org-heading-keyword-regexp-format’
Warning (bytecomp): reference to free variable ‘org-todo-regexp’
Warning (bytecomp): reference to free variable ‘org-done-keywords’
Warning (bytecomp): reference to free variable ‘org-activate-links’
Warning (bytecomp): reference to free variable ‘org-font-lock-extra-keywords’
Warning (bytecomp): assignment to free variable ‘org-font-lock-extra-keywords’
Warning (bytecomp): assignment to free variable ‘org-hide-leading-stars’
Warning (bytecomp): assignment to free variable ‘org-hide-leading-stars-before-indent-mode’
Warning (bytecomp): assignment to free variable ‘org-fontify-done-headline’
Warning (bytecomp): assignment to free variable ‘org-fontify-quote-and-verse-blocks’
Warning (bytecomp): assignment to free variable ‘org-fontify-whole-heading-line’
Warning (bytecomp): assignment to free variable ‘org-agenda-deadline-faces’
Warning (bytecomp): the function ‘org-delete-all’ is not known to be defined.
Warning (bytecomp): assignment to free variable ‘git-commit-post-finish-hook’
Warning (bytecomp): Unused lexical argument ‘value’
Warning (bytecomp): Unused lexical argument ‘key’
Warning (bytecomp): defcustom for ‘dumb-jump-ivy-jump-to-selected-function’ fails to specify type [2 times]
Warning (bytecomp): Unused lexical argument ‘config’
Warning (bytecomp): ‘find-tag-marker-ring’ is an obsolete variable (as of 25.1); use ‘xref-push-marker-stack’ or ‘xref-pop-marker-stack’ instead.
Warning (bytecomp): Unused lexical argument ‘lang’
Warning (bytecomp): Unused lexical argument ‘cur-file’
Warning (bytecomp): Unused lexical argument ‘exclude-paths’
Warning (bytecomp): Unused lexical argument ‘lang’
Warning (bytecomp): the function ‘helm-build-sync-source’ is not known to be defined.
Warning (bytecomp): Unused lexical variable ‘end-line’
Warning (bytecomp): Unused lexical variable ‘allowed-open’
Warning (bytecomp): Unused lexical variable ‘allowed-close’
Warning (bytecomp): reference to free variable ‘highlight-indent-guides-mode’
Warning (bytecomp): ‘font-lock-fontify-buffer’ is for interactive use only; use ‘font-lock-ensure’ or ‘font-lock-flush’ instead.
Warning (bytecomp): reference to free variable ‘mc/cmds-to-run-once’
Warning (bytecomp): assignment to free variable ‘mc/cmds-to-run-once’
Warning (bytecomp): assignment to free variable ‘iedit-initial-string-local’
Warning (bytecomp): Unused lexical argument ‘include-deleted-frame’
Warning (bytecomp): the following functions are not known to be defined: make-xwidget,
    set-xwidget-query-on-exit-flag, xwidget-webkit-mode,
    xwidget-webkit-goto-uri, xwidget-at,
    xwidget-webkit-execute-script, xwidget-webkit-execute-script-rv,
    xwidget-resize
Error (bytecomp): Cannot open load file: No such file or directory, flycheck
Warning (bytecomp): assignment to free variable ‘flycheck-display-errors-function’
Warning (bytecomp): the following functions are not known to be defined:
    flycheck-overlay-errors-in, flycheck-error-format-message-and-id,
    flycheck-error-level
Warning (bytecomp): defcustom for ‘lsp-metals-treeview-workspace-switch-delay’ fails to specify type
Warning (bytecomp): defcustom for ‘lsp-metals-treeview-workspace-switch-delay’ fails to specify containing group
Warning (bytecomp): defcustom for ‘lsp-metals-treeview-workspace-switch-delay’ fails to specify type
Warning (bytecomp): defcustom for ‘lsp-metals-treeview-workspace-switch-delay’ fails to specify containing group
Warning (bytecomp): ‘not’ called with 2 args, but requires 1
Warning (bytecomp): reference to free variable ‘lsp-metals-treeview--visible\?’
Warning (bytecomp): reference to free variable ‘treemacs-metals-node-closed-state’
Warning (bytecomp): reference to free variable ‘treemacs-metals-leaf-state’
Warning (bytecomp): the function ‘treemacs-parent-of’ is not known to be defined.
Warning (bytecomp): Unused lexical variable ‘session’
Warning (bytecomp): value returned from (aref theme 1) is unused
Warning (bytecomp): Unused lexical variable ‘buffer-changed’
Warning (bytecomp): ‘treemacs--get-children-of’ is an obsolete function (as of v2.7); use ‘treemacs-collect-child-nodes’ instead.
Warning (bytecomp): Unused lexical variable ‘name’
Warning (bytecomp): ‘treemacs--get-children-of’ is an obsolete function (as of v2.7); use ‘treemacs-collect-child-nodes’ instead.
Warning (bytecomp): Unused lexical variable ‘class’
Warning (bytecomp): Unused lexical variable ‘package’
Warning (bytecomp): Unused lexical variable ‘variables-reference’
Warning (bytecomp): Unused lexical variable ‘key’
Warning (bytecomp): Unused lexical argument ‘item’
Warning (bytecomp): function ‘lsp-treemacs--extract-line’ defined multiple times in this file
Warning (bytecomp): Unused lexical argument ‘item’
Error (bytecomp): Cannot open load file: No such file or directory, lsp-java
Warning (bytecomp): defcustom for ‘dap-debug-template-configurations’ fails to specify containing group [2 times]
Warning (bytecomp): ‘string-as-unibyte’ is an obsolete function (as of 26.1); use ‘encode-coding-string’.
Warning (bytecomp): dap-disconnect called with 0 arguments, but requires 1
Warning (bytecomp): Unused lexical variable ‘host’
Warning (bytecomp): Unused lexical variable ‘port’
Warning (bytecomp): Unused lexical variable ‘wait-for-port’
Warning (bytecomp): Unused lexical argument ‘debug-args’
Warning (bytecomp): Unused lexical variable ‘posframe-mouse-banish’
Warning (bytecomp): assignment to free variable ‘posframe-mouse-banish’
Warning (bytecomp): Unused lexical argument ‘args’ [8 times]
Warning (bytecomp): Unused lexical argument ‘result’
Warning (bytecomp): Unused lexical argument ‘args’
Warning (bytecomp): Unused lexical variable ‘indexed-variables’
Warning (bytecomp): Unused lexical argument ‘args’
Warning (bytecomp): the function ‘posframe-poshandler-frame-top-center’ is not known to be defined.
Warning (bytecomp): assignment to free variable ‘type’
Warning (bytecomp): reference to free variable ‘type’
Warning (bytecomp): defcustom for ‘company-box-doc-delay’ fails to specify type [2 times]
Warning (bytecomp): the function ‘icons-in-terminal’ is not known to be defined.
Warning (bytecomp): cl package required at runtime
Warning (bytecomp): Unused lexical argument ‘command’
Warning (bytecomp): Unused lexical argument ‘server’
Warning (bytecomp): Unused lexical argument ‘command’
Warning (bytecomp): Unused lexical argument ‘server’
Warning (bytecomp): Lexical argument shadows the dynamic variable major-mode
Warning (bytecomp): Unused lexical argument ‘filename’
Warning (bytecomp): the function ‘seq-first’ is not known to be defined.
Warning (bytecomp): Unused lexical argument ‘command’ [2 times]
Warning (bytecomp): Unused lexical argument ‘workspace’
Warning (bytecomp): Unused lexical argument ‘file-uri’
Warning (bytecomp): Unused lexical argument ‘command’ [2 times]
Warning (bytecomp): Unused lexical variable ‘end’
Warning (bytecomp): Unused lexical variable ‘static\?’
Warning (bytecomp): Unused lexical variable ‘setter\?’
Warning (bytecomp): Unused lexical variable ‘getter\?’
Warning (bytecomp): Unused lexical variable ‘member-type’
Warning (bytecomp): Unused lexical variable ‘display-name’
Warning (bytecomp): Unused lexical argument ‘workspace’
Warning (bytecomp): Unused lexical variable ‘package-name’
Warning (bytecomp): Unused lexical variable ‘java-version’
Warning (bytecomp): Unused lexical variable ‘description’
Warning (bytecomp): the function ‘helm-make-source’ is not known to be defined.
Warning (bytecomp): defcustom for ‘lsp-jt-theme’ fails to specify containing group [2 times]
Warning (bytecomp): Unused lexical argument ‘modified\?’
Warning (bytecomp): value returned from (aref theme 1) is unused
Warning (bytecomp): Unused lexical variable ‘project’
Warning (bytecomp): Unused lexical variable ‘node’
Warning (bytecomp): ‘treemacs--get-children-of’ is an obsolete function (as of v2.7); use ‘treemacs-collect-child-nodes’ instead.
Warning (bytecomp): the function ‘json-serialize’ is not known to be defined.
Warning (bytecomp): Unused lexical variable ‘pad’
Warning (bytecomp): Unused lexical variable ‘line’
Warning (bytecomp): Unused lexical variable ‘point1’
Warning (bytecomp): Unused lexical variable ‘point0’
Warning (bytecomp): Unused lexical variable ‘ranges’
Warning (bytecomp): reference to free variable ‘cur-buffer-workspaces’
Warning (bytecomp): defcustom for ‘ccls-initialization-options’ fails to specify type [2 times]
Warning (bytecomp): reference to free variable ‘go--case-or-default-regexp’
Warning (bytecomp): reference to free variable ‘go--case-regexp’
Warning (bytecomp): reference to free variable ‘go--comment-start-regexp’ [4 times]
Warning (bytecomp): reference to free variable ‘go--case-or-default-regexp’
Warning (bytecomp): ‘find-tag’ is an obsolete function (as of 25.1); use ‘xref-find-definitions’ instead. [2 times]
Warning (bytecomp): ‘show-entry’ is an obsolete function (as of 25.1); use ‘outline-show-entry’ instead.
Warning (bytecomp): reference to free variable ‘LaTeX-label-list’
Warning (bytecomp): reference to free variable ‘TeX-master’
Warning (bytecomp): reference to free variable ‘BibTeX-auto-regexp-list’
Warning (bytecomp): reference to free variable ‘TeX-header-end’
Warning (bytecomp): reference to free variable ‘LaTeX-header-end’
Warning (bytecomp): assignment to free variable ‘TeX-header-end’
Warning (bytecomp): the following functions are not known to be defined:
    reftex-view-crossref, extent-string, TeX-master-file,
    TeX-auto-write
Warning (bytecomp): global/dynamic var ‘reference’ lacks a prefix
Warning (bytecomp): global/dynamic var ‘title’ lacks a prefix
Warning (bytecomp): global/dynamic var ‘name’ lacks a prefix
Warning (bytecomp): global/dynamic var ‘level’ lacks a prefix
Warning (bytecomp): reference to free variable ‘ConTeXt-extra-paragraph-commands’
Warning (bytecomp): reference to free variable ‘font-latex-fontify-sectioning’
Warning (bytecomp): the following functions are not known to be defined:
    face-property-instance, set-face-property
Warning (bytecomp): global/dynamic var ‘title’ lacks a prefix
Warning (bytecomp): global/dynamic var ‘name’ lacks a prefix
Warning (bytecomp): global/dynamic var ‘level’ lacks a prefix
Warning (bytecomp): global/dynamic var ‘toc’ lacks a prefix
Warning (bytecomp): reference to free variable ‘TeX-auto-file’
Warning (bytecomp): assignment to free variable ‘TeX-auto-file’
Warning (bytecomp): assignment to free variable ‘TeX-auto-update’
Warning (bytecomp): assignment to free variable ‘LaTeX-section-list-changed’
Warning (bytecomp): the function ‘turn-off-filladapt-mode’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘preview-menu’
Warning (bytecomp): reference to free variable ‘preview-dumped-alist’
Warning (bytecomp): reference to free variable ‘preview-auto-reveal’
Warning (bytecomp): the following functions are not known to be defined:
    preview-filter-specs-1, preview-format-kill, preview-delete,
    preview-relaxed-string=, preview-disable,
    preview-inactive-string, desktop-buffer-preview-misc-data,
    preview-filter-specs, preview-auto-reveal-p
Warning (bytecomp): reference to free variable ‘TeX-bar-TeX-all-button-alists’
Warning (bytecomp): reference to free variable ‘TeX-bar-LaTeX-all-button-alists’
Warning (bytecomp): ‘font-lock-maximum-size’ is an obsolete variable (as of 24.1).
Warning (bytecomp): defface for ‘tex-math-face’ fails to specify containing group
Warning (bytecomp): reference to free variable ‘reftex-label-alist-builtin’
Warning (bytecomp): assignment to free variable ‘reftex-label-alist-builtin’
Warning (bytecomp): assignment to free variable ‘TeX-auto-update’
Warning (bytecomp): ‘TeX-Omega-mode’ is an obsolete function (as of 11.86); use ‘TeX-engine-set’ instead. [6 times]
Warning (bytecomp): reference to free variable ‘exit-mark’
Warning (bytecomp): assignment to free variable ‘last-optional-rejected’
Warning (bytecomp): reference to free variable ‘exit-mark’
Warning (bytecomp): assignment to free variable ‘ispell-tex-p’
Warning (bytecomp): assignment to free variable ‘TeX-auto-update’
Warning (bytecomp): reference to free variable ‘tex--prettify-symbols-alist’
Warning (bytecomp): reference to free variable ‘texmathp-why’
Warning (bytecomp): ‘inactivate-input-method’ is an obsolete function (as of 24.3); use ‘deactivate-input-method’ instead.
Warning (bytecomp): assignment to free variable ‘LaTeX-includegraphics-global-files’
Warning (bytecomp): the following functions are not known to be defined:
    tex--prettify-symbols-compose-p, spell-buffer
Warning (bytecomp): ‘indent-relative-maybe’ is an obsolete function (as of 26.1); use ‘indent-relative-first-indent-point’ instead. [3 times]
Warning (bytecomp): ‘previous-line’ is for interactive use only; use ‘forward-line’ with negative argument instead.
Warning (bytecomp): reference to free variable ‘environment’
Warning (bytecomp): reference to free variable ‘exit-mark’
Warning (bytecomp): reference to free variable ‘LaTeX-kpfonts-mode-menu’
Warning (bytecomp): reference to free variable ‘LaTeX-kpfonts-mode-map’
Warning (bytecomp): ‘indent-relative-maybe’ is an obsolete function (as of 26.1); use ‘indent-relative-first-indent-point’ instead. [2 times]
Warning (bytecomp): reference to free variable ‘TeX-TikZ-point-function-map’
Warning (bytecomp): reference to free variable ‘ConTeXt-indent-test/in’
Warning (bytecomp): reference to free variable ‘ConTeXt-indent-test/out’
Warning (bytecomp): the function ‘AUCTeX-set-ert-path’ is not known to be defined.
Warning (bytecomp): assignment to free variable ‘japanese-TeX-error-messages’
Warning (bytecomp): reference to free variable ‘parse-timing’
Warning (bytecomp): reference to free variable ‘reftex-docstruct-symbol’
Warning (bytecomp): the function ‘AUCTeX-set-ert-path’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘platex-shift-jis’
Warning (bytecomp): reference to free variable ‘different-coding-system’
Warning (bytecomp): reference to free variable ‘preserve-kanji-option’
Warning (bytecomp): the function ‘AUCTeX-set-ert-path’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘LaTeX-indent-tabular-test/in’
Warning (bytecomp): reference to free variable ‘LaTeX-indent-tabular-test/out’
Warning (bytecomp): reference to free variable ‘LaTeX-math-indent/in’
Warning (bytecomp): reference to free variable ‘LaTeX-math-indent/out’
Warning (bytecomp): reference to free variable ‘LaTeX-filling/in’
Warning (bytecomp): reference to free variable ‘LaTeX-filling/out’
Warning (bytecomp): reference to free variable ‘tabular-count-ampersands/in’
Warning (bytecomp): reference to free variable ‘tabular-count-ampersands/out’
Warning (bytecomp): the following functions are not known to be defined:
    AUCTeX-set-ert-path, LaTeX-includegraphics-extensions-list
Warning (bytecomp): reference to free variable ‘TeX-test-compilation-log’
Warning (bytecomp): the function ‘AUCTeX-set-ert-path’ is not known to be defined.
Error (bytecomp): Cannot open load file: No such file or directory, flycheck [32 times]
Warning (bytecomp): ‘font-lock-fontify-buffer’ is for interactive use only; use ‘font-lock-ensure’ or ‘font-lock-flush’ instead. [2 times]
Warning (bytecomp): ‘syntax-begin-function’ is an obsolete variable (as of 25.1).
Warning (bytecomp): the function ‘flyspell-generic-progmode-verify’ is not known to be defined.
Warning (bytecomp): function ‘reduce’ from cl package called at runtime
Warning (bytecomp): function ‘every’ from cl package called at runtime
Warning (bytecomp): function ‘equalp’ from cl package called at runtime
Warning (bytecomp): function ‘subseq’ from cl package called at runtime
Warning (bytecomp): function ‘remove-duplicates’ from cl package called at runtime [2 times]
Warning (bytecomp): function ‘subseq’ from cl package called at runtime [4 times]
Warning (bytecomp): function ‘find’ from cl package called at runtime
Warning (bytecomp): function ‘subseq’ from cl package called at runtime [2 times]
Warning (bytecomp): function ‘position’ from cl package called at runtime
Warning (bytecomp): function ‘subseq’ from cl package called at runtime [4 times]
Warning (bytecomp): reference to free variable ‘info’
Warning (bytecomp): defcustom for ‘plantuml-indent-level’ fails to specify type [2 times]
Warning (bytecomp): Unused lexical argument ‘status’
Warning (bytecomp): reference to free variable ‘plantuml-indent-regexp-end’
Warning (bytecomp): reference to free variable ‘plantuml-indent-regexp-start’
Warning (bytecomp): defcustom for ‘erc-image-images-path’ fails to specify type [2 times]
Warning (bytecomp): Unused lexical argument ‘marker’
Warning (bytecomp): ‘make-variable-buffer-local’ not called at toplevel
Warning (bytecomp): Unused lexical argument ‘proc’
Warning (bytecomp): Unused lexical argument ‘level’
Warning (bytecomp): Unused lexical argument ‘id’
Warning (bytecomp): the function ‘alert--log-enable-logging’ is not known to be defined.
Error (bytecomp): Cannot open load file: No such file or directory, mu4e [2 times]
Warning (bytecomp): the following functions are not known to be defined:
    pyim-pinyin2cchar-get, pyim-list-merge
Warning (bytecomp): reference to free variable ‘pattern’
Warning (bytecomp): assignment to free variable ‘prev-point’
Warning (bytecomp): reference to free variable ‘prev-point’
Warning (bytecomp): the function ‘pyim-pinyin2cchar-get’ is not known to be defined.
Warning (bytecomp): reference to free variable ‘pyim-punctuation-dict’ [2 times]
Warning (bytecomp): the following functions are not known to be defined:
    pyim-char-before-to-string, pyim-entered-get,
    evil-normal-state-p
Warning (bytecomp): defcustom for ‘pyim-default-scheme’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-assistant-scheme’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-schemes’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-fuzzy-pinyin-alist’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-english-input-switch-functions’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-punctuation-half-width-functions’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-page-tooltip’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-page-select-word-by-number’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-magic-converter’ fails to specify type [2 times]
Warning (bytecomp): defcustom for ‘pyim-autoselector’ fails to specify type [2 times]
Warning (bytecomp): assignment to free variable ‘pos’
Warning (bytecomp): reference to free variable ‘pos’
Warning (bytecomp): reference to free variable ‘hightlight-current’
Warning (bytecomp): the following functions are not known to be defined: posframe-hide,
    liberime-process-key, liberime-get-context, posframe-show,
    liberime-select-candidate`

Closing and launching the programme again generates the following warnings:

`Leaving directory ‘/home/giuliocentorame/.emacs.d/elpa/flycheck-20191126.2142’

Compiling file /home/giuliocentorame/.emacs.d/elpa/flycheck-20191126.2142/flycheck-ert.el at Fri Jan 10 18:15:59 2020
Entering directory ‘/home/giuliocentorame/.emacs.d/elpa/flycheck-20191126.2142/’

Compiling file /home/giuliocentorame/.emacs.d/elpa/flycheck-20191126.2142/flycheck.el at Fri Jan 10 18:16:00 2020

Compiling no file at Fri Jan 10 18:16:02 2020
Leaving directory ‘/home/giuliocentorame/.emacs.d/elpa/org-edit-latex-20170908.1522’

Compiling file /home/giuliocentorame/.emacs.d/elpa/org-edit-latex-20170908.1522/org-edit-latex.el at Fri Jan 10 18:16:02 2020
Entering directory ‘/home/giuliocentorame/.emacs.d/elpa/org-edit-latex-20170908.1522/’
Warning (bytecomp): the function ‘org-eldoc-documentation-function’ is not known to be defined.`

They cease at the third launch.

**To Reproduce**
Fresh-installed M-EMACS as per instructions.

**Versions (please complete the following information):**
 - OS and/or Distros: Linux Manjaro xfce
 - GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29
 
**Additional context**
I am not sure it affects the functionality at all, but I was able to reproduce the same warnings twice on my workstation even after removing my `.gitignore` (I thought I was doing some mess with a dotfile).

**Comment by MatthewZMD** [comment]
Oh, nothing is wrong here.

When you start Emacs, Emacs is gonna download and compile a lot of third-party packages from elpa and melpa. Since they are third-party packages, some code isn't perfect and has minor issues that is caught by Emacs which generates a warning. Since these are warnings and not errors, it will not affect your usage.

It's just a small annoyance when you install and upgrade packages. Simply focus on the warning buffer and enter `q` to quit that buffer, then you are good to go.
