### ISSUE TITLE
org-hide-leading-stars is overridden with a buffer local variable.

### ISSUE THREAD

**Issue by neilyio** [MatthewZMD/.emacs.d#28]
I just got started with M-EMACS. I'm mostly very happy with the config, but have made some minor changes for org-mode. I simply added these into the init.el, and for the most part they load fine.

`;;; Org-mode preferences
(with-eval-after-load 'org
  (add-hook 'org-mode-hook 'org-indent-mode)
  (add-hook 'org-mode-hook 'visual-line-mode)
  (add-hook 'org-mode-hook (lambda () (display-line-numbers-mode -1)))
  (add-hook 'org-mode-hook (lambda () (setq org-hide-leading-stars nil))))`

The only thing that's not working for me is org-hide-leading-stars. Even when I set it to nil as a global variable, every time I open an org-mode buffer I'm finding that it is changed back to t in a buffer-local variable.

Something seems to be overriding my (setq org-hide-leading-stars nil). Would love some input!

By the way, so far this is been the greatest Emacs config I've ever seen. Looking forward to spreading the word.

**Comment by MatthewZMD** [comment]
> By the way, so far this is been the greatest Emacs config I've ever seen. Looking forward to spreading the word.

Thanks for using M-EMACS, this is super heartwarming!

> (add-hook 'org-mode-hook (lambda () (setq org-hide-leading-stars nil)))`

Actually, you don't need to add this to `org-mode-hook`, `org-hide-leading-stars` is an `org-mode` specific variable, simply add `(setq org-hide-leading-stars nil))` to the config does the job. If you want, you can append `(org-hide-leading-stars nil)` under `:custom` in `init-org.el` instead of `init.el` too.

**Comment by neilyio** [comment]
I found the solution, just wanted to follow up in case anyone else runs into this.

My issue was with a default behavior of org-indent-mode. In org-indent.el, we can find:
https://github.com/emacs-mirror/emacs/blob/baca81e64141aed076fe088e7160f6e0d4a51c68/lisp/org/org-indent.el#L182-L185

And sure enough, the default value of `org-indent-mode-turns-on-hiding-stars` is t:

https://github.com/emacs-mirror/emacs/blob/baca81e64141aed076fe088e7160f6e0d4a51c68/lisp/org/org-indent.el#L96-L100

To fix the problem, you need to address both `org-hide-leading-stars` and `org-indent-mode-turns-on-hiding-stars`:

```elisp
(setq org-hide-leading-stars nil)
(setq org-indent-mode-turns-in-hiding-stars nil)
```

This should really be documented at https://orgmode.org/manual/Clean-view.html, which suggests that `(setq org-hide-leading-stars nil)` by itself will bring the stars back. I'll reach out.

**Comment by bzg** [comment]
This will be documented in the next release of `Org 9.3.2' - thanks again for reporting this on the orgmode mailing list, that's really where things happen.

**Comment by MatthewZMD** [comment]
Good to hear that is been taken cared of by org-mode upstream :)
