### ISSUE TITLE
use general for key binging

### ISSUE THREAD

**Issue by matsievskiysv** [MatthewZMD/.emacs.d#29]
It might be a good idea to use [general](https://github.com/noctuid/general.el) for key binding.
It provides some nice features and has `use-package` integration.

**Comment by MatthewZMD** [comment]
My concern is this will go through so much hassle to convert all existing config into general. The features in README do not convince me yet.

**Comment by seregaxvm** [comment]
General advantage is that it handles regular and [evil](https://github.com/emacs-evil/evil) key bindings in (almost) same way. Converting existing key bindings to evil mode maps would be easier.

**Comment by MatthewZMD** [comment]
Closed as not planned.
