### ISSUE TITLE
What is the recommended workflow for keeping my forked version up to date?

### ISSUE THREAD

**Issue by BilaalHussain** [MatthewZMD/.emacs.d#30]
I have my own branch with my custom keybinds. When I try to rebase or merge, there are many conflicts. Is there a way to circumvent this

**Comment by MatthewZMD** [comment]
The first thing to do is to ignore all `README.md` and `init.org` conflicts. In magit, point to the file and press `k` to drop changes. And the rest really depends on your local changes, magit really comes in handy
