### ISSUE TITLE
Add example for how to disable packages in init.org

### ISSUE THREAD

**Issue by BilaalHussain** [MatthewZMD/.emacs.d#31]
As someone who doesn't use org mode, I'm not sure how to disable packages. I did 
![image](https://user-images.githubusercontent.com/24777811/82082259-af266f00-96b5-11ea-8448-f92b5f84984a.png), but it seems like the package is still loaded in (i can use the commands for it)
is there a way to not run the init elisp for that package?

**Comment by MatthewZMD** [comment]
`:disabled` tag needed to be put inside the lisp code, within `use-package`. See `elisp/init-ein.el` as an example.

**Comment by BilaalHussain** [comment]
Worked. Thanks!
