### ISSUE TITLE
Chinese characters present even when pyim disabled

### ISSUE THREAD

**Issue by BilaalHussain** [MatthewZMD/.emacs.d#32]
Hi, I would like to not have chinese characters in my UI, but I cannot find out how to disable them.

I added the :disabled tag in init-pyim.el for pyim-basedict, but I still see these characters e.g. 
![image](https://user-images.githubusercontent.com/24777811/82093738-afc90080-96c9-11ea-8997-cc21b09cca34.png)

Please advise,
thanks.

**Comment by MatthewZMD** [comment]
I don't think that's legit Chinese characters, they're random UTF8 codes because it's likely you don't have the icons correctly set-up. See *Fonts and Icons* section in the README.

**Comment by BilaalHussain** [comment]
Thanks! I've never installed fonts before so I assumed that just having them in the directory would be fine.
