### ISSUE TITLE
Use package "try"

### ISSUE THREAD

**Issue by BilaalHussain** [MatthewZMD/.emacs.d#33]
- I like to experiment with different packages sometimes when tinkering around (e.g. multiple cursors)
- It is inconvenient to delete the package after I am done with it

- I think adding adding (use-package try) would be good. Perhaps in init-package.el? 

-Let me know if you disagree, else I can make a PR for it.

**Comment by MatthewZMD** [comment]
If you want to easily experiment and then delete a package, you should use `M-x counsel-package`, it comes with M-EMACS by default :-)
