### ISSUE TITLE
Supply dashboard-agenda info re: Org mode in README 

### ISSUE THREAD

**Issue by aahamlin** [MatthewZMD/.emacs.d#37]
I am not sure how/if you take feedback on the readme and/or configuration org file but I'm assuming it would help other newer users (like me) to mention that the dashboard agenda widget only shows agenda items tagged with DEADLINE or SCHEDULED, as mentioned in [Dashboard Issue 226](https://github.com/emacs-dashboard/emacs-dashboard/issues/226).

**Comment by MatthewZMD** [comment]
Good idea, thanks for letting me know :)
