### ISSUE TITLE
Can not get auto-complete. It just shows "$" instead of options. 

### ISSUE THREAD

**Issue by d3v-S** [MatthewZMD/.emacs.d#38]
**Describe the bug**

**To Reproduce**
Normal installation.

**Expected behavior**
drop-down showing options.

**Screenshots**
![emacs_memacs_autocomplete](https://user-images.githubusercontent.com/67001383/95670246-63b1b780-0ba6-11eb-9edb-6e2b9024ce41.png)

**Versions (please complete the following information):**
 - OS and/or Distros: xfce4 20.04
 - M-x emacs-version 26.3

**Comment by MatthewZMD** [comment]
Did you follow the `Prerequisite` instructions?

**Comment by d3v-S** [comment]
Yes I did.

These are correct suggestions, but I can not see them. If i press down and RET, then one of the struct memeber is selected. but I can not seem to see them.

**Comment by MatthewZMD** [comment]
You're running Emacs in GUI, right?

**Comment by MatthewZMD** [comment]
This looks like a issue likely related to company-box, I've never seen it, have you? @sebastiencs

**Comment by d3v-S** [comment]
Yes. I am running it in GUI. 

DE is xfce4.

I tried tabnine, same issue. Changed it to company-lsp. Still the same issue. 

Should I remove company-box?

**Comment by MatthewZMD** [comment]
> Changed it to company-lsp. Still the same issue.

`company-lsp` does not exist on the current version of M-EMACS anymore. Did you `git pull`?

**Comment by d3v-S** [comment]
I had changed it as it was working in my old config.

lsp + ccls + company_lsp.

I had thought it was an issue of tabnine thats why.

**Comment by MatthewZMD** [comment]
Then I suggest you remove company-lsp or rebase my latest commits soon, as company-lsp is officially deprecated and no longer supported by the lsp-mode team. There are weird bugs with it here and there.

**Comment by d3v-S** [comment]
> I don't think it's the problem with the backends, as you say you can select the completing suggestions, but it just didn't appear at the frontend.

Yes that I realised after changing it to company-lsp. Did changed it back to default. But same $.

**Comment by d3v-S** [comment]
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "ol")
  require(ol)
  eval-buffer(#<buffer  *load*-460722> nil "/home/d3v/.emacs.d/site-elisp/emacs-application-framework/eaf-org.el" nil t)  ; Reading at buffer position 1436
  load-with-code-conversion("/home/d3v/.emacs.d/site-elisp/emacs-application-framework/eaf-org.el" "/home/d3v/.emacs.d/site-elisp/emacs-application-framework/eaf-org.el" nil t)
  require(eaf-org)
  (progn (funcall (or (get (quote eaf-find-alternate-file-in-dired) (quote custom-set)) (function set-default)) (quote eaf-find-alternate-file-in-dired) t) (funcall (or (get (quote browse-url-browser-function) (quote custom-set)) (function set-default)) (quote browse-url-browser-function) (quote eaf-open-browser)) (funcall (or (get (quote eaf-browser-continue-where-left-off) (quote custom-set)) (function set-default)) (quote eaf-browser-continue-where-left-off) t) (use-package-statistics-gather :init (quote eaf) nil) (require (quote eaf) nil nil) (use-package-statistics-gather :config (quote eaf) nil) (require (quote eaf-org)) (defalias (quote browse-web) (function eaf-open-browser)) (eaf-setq eaf-browser-default-zoom "1.25") (eaf-setq eaf-browser-dark-mode "false") (eaf-setq eaf-browser-enable-adblocker "true") (eaf-setq eaf-pdf-dark-mode "false") (eaf-setq eaf-browser-enable-autofill "true") (eaf-bind-key nil "M-q" eaf-browser-keybinding) (eaf-bind-key open_link "C-M-s" eaf-browser-keybinding) (eaf-bind-key clear_cookies "C-M-q" eaf-browser-keybinding) (eaf-bind-key insert_or_recover_prev_close_page "X" eaf-browser-keybinding) (eaf-bind-key scroll_up "RET" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_down_page "DEL" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_down_page "u" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_up_page "d" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_to_end "M->" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_to_begin "M-<" eaf-pdf-viewer-keybinding) (eaf-bind-key quit-window "q" eaf-pdf-viewer-keybinding) (eaf-bind-key zoom_in "C-=" eaf-pdf-viewer-keybinding) (eaf-bind-key zoom_out "C--" eaf-pdf-viewer-keybinding) (eaf-bind-key take_photo "p" eaf-camera-keybinding) (eaf-bind-key eaf-send-key-sequence "M-]" eaf-terminal-keybinding) t (use-package-statistics-gather :config (quote eaf) t) (use-package-statistics-gather :init (quote eaf) t))
  (if (symbol-value (quote eaf-env-p)) (progn (funcall (or (get (quote eaf-find-alternate-file-in-dired) (quote custom-set)) (function set-default)) (quote eaf-find-alternate-file-in-dired) t) (funcall (or (get (quote browse-url-browser-function) (quote custom-set)) (function set-default)) (quote browse-url-browser-function) (quote eaf-open-browser)) (funcall (or (get (quote eaf-browser-continue-where-left-off) (quote custom-set)) (function set-default)) (quote eaf-browser-continue-where-left-off) t) (use-package-statistics-gather :init (quote eaf) nil) (require (quote eaf) nil nil) (use-package-statistics-gather :config (quote eaf) nil) (require (quote eaf-org)) (defalias (quote browse-web) (function eaf-open-browser)) (eaf-setq eaf-browser-default-zoom "1.25") (eaf-setq eaf-browser-dark-mode "false") (eaf-setq eaf-browser-enable-adblocker "true") (eaf-setq eaf-pdf-dark-mode "false") (eaf-setq eaf-browser-enable-autofill "true") (eaf-bind-key nil "M-q" eaf-browser-keybinding) (eaf-bind-key open_link "C-M-s" eaf-browser-keybinding) (eaf-bind-key clear_cookies "C-M-q" eaf-browser-keybinding) (eaf-bind-key insert_or_recover_prev_close_page "X" eaf-browser-keybinding) (eaf-bind-key scroll_up "RET" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_down_page "DEL" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_down_page "u" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_up_page "d" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_to_end "M->" eaf-pdf-viewer-keybinding) (eaf-bind-key scroll_to_begin "M-<" eaf-pdf-viewer-keybinding) (eaf-bind-key quit-window "q" eaf-pdf-viewer-keybinding) (eaf-bind-key zoom_in "C-=" eaf-pdf-viewer-keybinding) (eaf-bind-key zoom_out "C--" eaf-pdf-viewer-keybinding) (eaf-bind-key take_photo "p" eaf-camera-keybinding) (eaf-bind-key eaf-send-key-sequence "M-]" eaf-terminal-keybinding) t (use-package-statistics-gather :config (quote eaf) t) (use-package-statistics-gather :init (quote eaf) t)))
  eval-buffer(#<buffer  *load*-264376> nil "/home/d3v/.emacs.d/elisp/init-eaf.el" nil t)  ; Reading at buffer position 3215
  load-with-code-conversion("/home/d3v/.emacs.d/elisp/init-eaf.el" "/home/d3v/.emacs.d/elisp/init-eaf.el" nil t)
  require(init-eaf)
  eval-buffer(#<buffer  *load*> nil "/home/d3v/.emacs.d/init.el" nil t)  ; Reading at buffer position 5344
  load-with-code-conversion("/home/d3v/.emacs.d/init.el" "/home/d3v/.emacs.d/init.el" t t)
  load("/home/d3v/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1e0f4d>)()
  command-line()
  normal-top-level()



I got this error when re-installing it.  Have I missed something in pre-requisites?

**Comment by MatthewZMD** [comment]
Can you simply run `M-: (require 'ol)`?

**Comment by d3v-S** [comment]
"Trailing garbage following expression"

**Comment by d3v-S** [comment]
This is not the perfect place to say this, but thanks for this configuration. My previous configuration had some parts, directly copied from yours (EAF to be precise)  and the quick replies here are simply awesome. Thank you for helping a guy out and for sharing this. I hope this evolves to be into something really big. 

anyways back to problem xD.

**Comment by MatthewZMD** [comment]
> This is not the perfect place to say this, but thanks for this configuration. My previous configuration had some parts, directly copied from yours (EAF to be precise) and the quick replies here are simply awesome. Thank you for helping a guy out and for sharing this. I hope this evolves to be into something really big.

No problem, and thank you for your kind words!! :heart: :heart:

Can you try both `(require 'ol-docview)` and `(require 'org-docview)` and see which one comes up? I just checked that emacs26.3 does not have `emacs/lisp/org/ol.el` built-in, but I forgot what was the replacement, and then I'll fix the EAF side.

**Comment by d3v-S** [comment]
Both of them are giving "Trailing ... " error. Should I update my emacs?

**Comment by MatthewZMD** [comment]
> Should I update my emacs?

Sure, if you could.

But I still want to fix this issue on the EAF side. Before you make the upgrade, can you restart Emacs and try to `(require ...)` again, if the error persists can you check your `emacs_dir/lisp/org` and tell me whether there exists a file `org-docview` (or something similar)

**Comment by d3v-S** [comment]
d3v@pc:/usr/share/emacs/26.3$ find . -name "*docview*"
./lisp/org/org-docview.el.gz
./lisp/org/org-docview.elc


org-docview seems to be here. 
but require 'org-docview still gives "trailing .. " error.

**Comment by MatthewZMD** [comment]
That definitely is an emacs issue. :( Just upgrade to 27.1, if you can

**Comment by d3v-S** [comment]
updated to 27,1, issue seems to be resolved. 

Now having issues with tabnine, wrong predictions. How can we change the default backend?  multiple "M-q" is hanging emacs.

**Comment by MatthewZMD** [comment]
What do you mean by wrong predictions? Tabnine is powered by machine learning and the prediction will never be 100% accurate as to what you're thinking in your head ;)

**Comment by d3v-S** [comment]
> What do you mean by wrong predictions? Tabnine is powered by machine learning and the prediction will never be 100% accurate as to what you're thinking in your head ;)

Yes, as in - 
I have included a header file in C and a struct is defined in that file. tabnine is not predicting the struct member but "M-q" lets it print the options but sometimes multiple continuous "M-q" is making emacs unresponsive.

**Comment by MatthewZMD** [comment]
Is tabnine predicting _anything_?

M-EMACS combined lsp with tabinine, so that when you type anything, both backends work at the same time

**Comment by d3v-S** [comment]
> Is tabnine predicting _anything_?
> 
> M-EMACS combined lsp with tabinine, so that when you type anything, both backends work at the same time

Depends. Sometimes it is blank simply, then also pressing "M-q" works. But issue is sometimes pressing "M-q" multiple times simply hangs emacs. 

I shifted back to company-lsp, things seems to work properly with ccls.

**Comment by d3v-S** [comment]
Ohh yes and some times TabNine process takes up 100 percent CPU.

**Comment by MatthewZMD** [comment]
Maybe you should create an issue at company-tabnine or tabnine
