### ISSUE TITLE
undefined symbol: k5_externalize_context

### ISSUE THREAD

**Issue by vgivanovic** [MatthewZMD/.emacs.d#40]
**Describe the bug**
Clicking on the [M-EMACS] button on the dashboard, I get this error:
```
Traceback (most recent call last):
  File "/home/vladimir/.emacs.d/site-elisp/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa

  File "/home/vladimir/.emacs.d/site-elisp/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser import BrowserBuffer

  File "/home/vladimir/.emacs.d/site-elisp/emacs-application-framework/core/browser.py", line 25, in <module>
    from PyQt5.QtNetwork import QNetworkCookie

ImportError: /usr/lib/libgssapi_krb5.so.2: undefined symbol: k5_externalize_context, version krb5_3_MIT
```

**To Reproduce**
1. Go to '~/'
2. Run `git clone --recurse-submodules -j8 https://github.com/MatthewZMD/.emacs.d.git`
3. `cd .emacs.d` and run `emacs`
4. Exit Emacs after it has build everything.
5. Restart `emacs`
5. See error (above).

**Expected behavior**
Don't know because I've never run M-EMACS before.

**Versions (please complete the following information):**
 - CPU: ```
Quad Core Intel Core i7-8809G (-MT MCP-) speed/min/max: 1400/800/8300 MHz Kernel: 5.9.11-arch2-1 x86_64 
Up: 20h 35m Mem: 14550.2/32028.2 MiB (45.4%) Storage: 24.81 TiB (16.8% used) Procs: 99 Shell: inxi: 3.1.04 

```
 - ```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3)
 of 2020-11-22
```

**Comment by MatthewZMD** [comment]
Do you intend to use EAF? If not simply change `:if eaf-env-p` to `:disabled`, as when you click on [M-EMACS], it tried to use the EAF Browser.

**Comment by MatthewZMD** [comment]
If you do intend to use EAF, it seems like you have PyQtWebEngine installed (so `eaf-env-p` evaluates to `t`, as it assumes people who has PyQtWebEngine will probably want to try out EAF), please make sure you've followed all the instructions on the EAF [README](https://github.com/manateelazycat/emacs-application-framework), if the problem persists, then fill an isseu at that repo.

**Comment by vgivanovic** [comment]
No, I don't intend to use EAF, so I can make the change. But a user shouldn't be presented with an error the first time they try to run M-EMACS, at least, I don't think they should.

**Comment by stardiviner** [comment]
I got same problem. Seems because I use Anaconda. When I `conda deactivate` to exit anaconda `base` virtual environment. The EAF start browser correctly.

**Comment by MatthewZMD** [comment]
Please raise this issue at the EAF repo.
