### ISSUE TITLE
Font is not quite monospaced

### ISSUE THREAD

**Issue by vgivanovic** [MatthewZMD/.emacs.d#41]
**Describe the bug**
Characters don't quite line up. This is easily visible in a `dired` buffer.

**To Reproduce**
1. run `emacs`
2. Execute `dired`

**Expected behavior**
I expect pixel-perfect alignment of glyphs. I've never seen a monospaced font used in Emacs which didn't align.

**Screenshots**

**Versions (please complete the following information):**
 - `CPU: Quad Core Intel Core i7-8809G (-MT MCP-) speed/min/max: 1400/800/8300 MHz Kernel: 5.9.11-arch2-1 x86_64 
Up: 20h 35m Mem: 14550.2/32028.2 MiB (45.4%) Storage: 24.81 TiB (16.8% used) Procs: 99 Shell: inxi: 3.1.04 `
 - `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3)
 of 2020-11-22`

**Comment by MatthewZMD** [comment]
Can you provide me a screenshot?

**Comment by MatthewZMD** [comment]
Closing due to unclear issue description.

**Comment by MatthewZMD** [comment]
Hi Vladimir, no problem, has the issue resolved for you yet?
