### ISSUE TITLE
How to disable or use keyboard to close pop out error message?

### ISSUE THREAD

**Issue by lanyusan** [MatthewZMD/.emacs.d#43]
It is getting annoying. How to disable the pop out error message in configuration or use keyboard to close it?

**Comment by MatthewZMD** [comment]
What is the error?

**Comment by lanyusan** [comment]
Sorry not specific enough. It is this:
![image](https://user-images.githubusercontent.com/56706512/109126466-38f88200-7788-11eb-8829-0cb94d8a043d.png)

**Comment by MatthewZMD** [comment]
Did you try `C-g`

**Comment by lanyusan** [comment]
Thanks for the fix. It is good enough for me.
