### ISSUE TITLE
Duplicate files in snippets/latex-mode causing problems in windows

### ISSUE THREAD

**Issue by BilaalHussain** [MatthewZMD/.emacs.d#46]
**Describe the bug**
snippets/latex-mode has files that only differ in case:

Iff
iff
Long-implies
long-implies
Implies
implies

It seems that these files are treated differently by git and windows, and when both were modified, checking out either one would cause the other to be treated as 'modified' by git. (Windows filesystem is case insensitive from my understanding)

Regardless, it seems that these duplicates are unnecessary? if not, I can investigate the problem more.

**Comment by MatthewZMD** [comment]
Yes, they're unnecessary, simply delete them if you want :)
