### ISSUE TITLE
usage question: how to start Tramp 

### ISSUE THREAD

**Issue by vladp** [MatthewZMD/.emacs.d#49]
Hello, trying Ctrl-c + Ctrl-f to start Tramp mode, but instead getting some reg-ex matching thing. 
How do I start tramp mode (sorry if the question has been answered, I searched docs, but did not see anything except gssh config (which I do not need).

env: Emacs 27.2 / Windows 10

**Comment by MatthewZMD** [comment]
You simpy type `/` 2 times to go the root directory, and follow it with `ssh:` or whatever.

**Comment by vladp** [comment]
thank you! That worked
