### ISSUE TITLE
mu4e short cut does not work, icon on the modeline show the inbox

### ISSUE THREAD

**Issue by wereket** [MatthewZMD/.emacs.d#53]
when I press ji I don't see the inbox
![image](https://user-images.githubusercontent.com/89839215/173205738-e22236d8-5ced-4d0a-ab32-a8d1ba71bab9.png)

when I press the envelope icons I see 
![image](https://user-images.githubusercontent.com/89839215/173205780-1b972565-2857-411d-84de-ce8e570722b2.png)

**Comment by wereket** [comment]
It works perfect now

**Comment by MatthewZMD** [comment]
Good to hear
