### ISSUE TITLE
Same key binding for projectile and yaml-mode

### ISSUE THREAD

**Issue by ibrevdo** [MatthewZMD/.emacs.d#56]
**Describe the bug**
The key binding "C-c p" is defined as projectile map command map, and also, as yaml-get-path-at-point

**To Reproduce**
Press "C-c p f"
As a result, 'f' is pressed

**Expected behavior**
The projectile-find-file should appear

**Comment by MatthewZMD** [comment]
I personally don't use `projectile` much. To find files, I recommend `ffip` binded to `C-z p`.

Regarding this problem, I can fix both ways, remove the binding in yaml-mode or remove the binding to projectile.

**Comment by ibrevdo** [comment]
I guess you can remove the binding from `projectile`.
According to [usage](https://docs.projectile.mx/projectile/usage.html), the key `S-p` is default.
Or, maybe you can use a binding `C-x p` for as it seems free.

**Comment by MatthewZMD** [comment]
Fixed in the latest commit, I used your `C-x p` idea. Thanks for the feedback!
